apiVersion: v1
kind: Service
metadata:
  name: spring-boot-session-azure-redis-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Port for LB 
      targetPort: 8080 # Port for Target Endpoint
  selector:
    app: spring-boot-session-azure-redis-app